/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlgorithmSelector: typeof import('./src/components/AlgorithmSelector.vue')['default']
    DateNavigation: typeof import('./src/components/DateNavigation.vue')['default']
    ErrorState: typeof import('./src/components/ErrorState.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    MonthNavigation: typeof import('./src/components/MonthNavigation.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShiftBadge: typeof import('./src/components/ShiftBadge.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    TimeDisplay: typeof import('./src/components/TimeDisplay.vue')['default']
  }
}
