version: '3.8'

services:
  # Django Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shift-manager-backend
    restart: unless-stopped
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - DJANGO_SETTINGS_MODULE=rostering_project.settings
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    expose:
      - "8000"
    networks:
      - shift-manager-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 rostering_project.wsgi:application"

  # Vue.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: shift-manager-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - shift-manager-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: shift-manager-nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - shift-manager-network

networks:
  shift-manager-network:
    driver: bridge 