# Generated by Django 5.1.7 on 2025-06-27 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_hours_per_week', models.IntegerField()),
                ('absences', models.JSONField(blank=True, default=list)),
                ('preferred_shifts', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EarlyShift', 'Early Shift'), ('LateShift', 'Late Shift'), ('NightShift', 'Night Shift')], max_length=20, unique=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('min_staff', models.IntegerField()),
                ('max_staff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('archived', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rostering_app.employee')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rostering_app.shifttype')),
            ],
        ),
    ]
