# Generated by Django 5.1.7 on 2025-06-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rostering_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(
                choices=[('EarlyShift', 'Early Shift'), ('LateShift', 'Late Shift'), ('NightShift', 'Night Shift')],
                max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('company', 'name')},
        ),
    ]
