# Generated by Django 5.1.7 on 2025-06-28 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rostering_app', '0002_alter_shift_name_alter_shift_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='archived',
        ),
    ]
