# Generated by Django 5.1.7 on 2025-06-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering_app', '0002_company_remove_scheduleentry_shift_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='rostering_app.company'),
        ),
    ]
