# Generated by Django 5.1.7 on 2025-06-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rostering_app', '0002_company_remove_scheduleentry_shift_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiftType',
        ),
    ]
