# Generated by Django 5.1.7 on 2025-06-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering_app', '0003_scheduleentry_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='algorithm',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
