# Generated by Django 5.1.7 on 2025-06-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering_app', '0004_company_sunday_is_workday_alter_shift_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(choices=[('EarlyShift', 'Frühschicht'), ('MorningShift', 'Morgenschicht'), ('LateShift', 'Spätschicht'), ('NightShift', 'Nachtschicht')], max_length=20),
        ),
    ]
