# Generated by Django 4.2.23 on 2025-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rostering_app', '0005_update_shift_names_to_german'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'),
                             ('failed', 'Failed')], default='idle', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('load_fixtures', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Benchmark Status',
            },
        ),
    ]
