# Generated by Django 4.2.23 on 2025-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rostering_app', '0006_benchmarkstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBenchmarkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('test_case', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company Benchmark Status',
            },
        ),
    ]
