# Generated by Django 4.2.23 on 2025-06-29 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rostering_app', '0007_companybenchmarkstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BenchmarkStatus',
        ),
        migrations.DeleteModel(
            name='CompanyBenchmarkStatus',
        ),
    ]
