# Generated by Django 4.2.23 on 2025-07-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering_app', '0008_delete_benchmarkstatus_delete_companybenchmarkstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='algorithm',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='scheduleentry',
            index_together={('company', 'date'), ('company', 'employee'), ('company', 'algorithm'), ('employee', 'date'), ('company', 'shift')},
        ),
    ]
