# Generated by Django 4.2.23 on 2025-07-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rostering_app', '0009_alter_scheduleentry_algorithm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('algorithm', models.CharField(blank=True, default='', max_length=64)),
                ('monthly_hours_worked', models.FloatField(default=0.0)),
                ('monthly_shifts', models.IntegerField(default=0)),
                ('expected_monthly_hours', models.FloatField(default=0.0)),
                ('overtime_hours', models.FloatField(default=0.0)),
                ('undertime_hours', models.FloatField(default=0.0)),
                ('utilization_percentage', models.FloatField(default=0.0)),
                ('absence_days', models.IntegerField(default=0)),
                ('days_worked', models.IntegerField(default=0)),
                ('possible_days', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_kpis', to='rostering_app.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='rostering_app.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'year', 'month'], name='rostering_a_company_cf4621_idx'), models.Index(fields=['employee', 'year', 'month'], name='rostering_a_employe_19b9a2_idx'), models.Index(fields=['algorithm'], name='rostering_a_algorit_0c076c_idx')],
                'unique_together': {('employee', 'company', 'year', 'month', 'algorithm')},
            },
        ),
        migrations.CreateModel(
            name='CoverageKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('algorithm', models.CharField(blank=True, default='', max_length=64)),
                ('total_working_days', models.IntegerField(default=0)),
                ('total_required_staff', models.IntegerField(default=0)),
                ('total_assigned_staff', models.IntegerField(default=0)),
                ('coverage_rate', models.FloatField(default=0.0)),
                ('understaffed_days', models.IntegerField(default=0)),
                ('overstaffed_days', models.IntegerField(default=0)),
                ('shift_coverage', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_kpis', to='rostering_app.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'start_date', 'end_date'], name='rostering_a_company_985e18_idx'), models.Index(fields=['algorithm'], name='rostering_a_algorit_ed17a4_idx')],
                'unique_together': {('company', 'start_date', 'end_date', 'algorithm')},
            },
        ),
        migrations.CreateModel(
            name='CompanyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('algorithm', models.CharField(blank=True, default='', max_length=64)),
                ('total_hours_worked', models.FloatField(default=0.0)),
                ('avg_hours_per_employee', models.FloatField(default=0.0)),
                ('hours_std_dev', models.FloatField(default=0.0)),
                ('hours_cv', models.FloatField(default=0.0)),
                ('gini_coefficient', models.FloatField(default=0.0)),
                ('min_hours', models.FloatField(default=0.0)),
                ('max_hours', models.FloatField(default=0.0)),
                ('total_weekly_violations', models.IntegerField(default=0)),
                ('rest_period_violations', models.IntegerField(default=0)),
                ('employee_hours', models.JSONField(blank=True, default=dict)),
                ('weekly_violations', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_kpis', to='rostering_app.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'year', 'month'], name='rostering_a_company_9f5b09_idx'), models.Index(fields=['algorithm'], name='rostering_a_algorit_99d37b_idx')],
                'unique_together': {('company', 'year', 'month', 'algorithm')},
            },
        ),
    ]
