# Generated by Django 4.2.23 on 2025-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rostering_app', '0010_employeekpi_coveragekpi_companykpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='companykpi',
            name='rest_period_violations_detailed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='companykpi',
            name='weekly_violations_detailed',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
