# Generated by Django 4.2.23 on 2025-07-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rostering_app', '0011_add_detailed_violations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeekpi',
            name='planned_absences',
            field=models.IntegerField(default=0),
        ),
    ]
