# Generated by Django 4.2.23 on 2025-08-01 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rostering_app', '0012_add_planned_absences_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coveragekpi',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coveragekpi',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='employeekpi',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeekpi',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employeekpi',
            name='employee',
        ),
        migrations.DeleteModel(
            name='CompanyKPI',
        ),
        migrations.DeleteModel(
            name='CoverageKPI',
        ),
        migrations.DeleteModel(
            name='EmployeeKPI',
        ),
    ]
